# Generated by Django 3.1.2 on 2020-11-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_content',
            name='decription',
        ),
        migrations.AddField(
            model_name='blog_content',
            name='decrip1',
            field=models.CharField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.', max_length=8000),
        ),
    ]
