# Generated by Django 3.1.2 on 2020-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201101_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
