# Generated by Django 3.1.2 on 2020-11-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201101_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='decrip1',
            field=models.TextField(default='لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.'),
        ),
    ]
