# Generated by Django 3.1.2 on 2020-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0003_auto_20201031_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='porto',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
